In [3]:
import numpy as np

# Vandermonde

In [14]:
x = np.array([1,2,3,4,5])
N = 5
data1 = np.column_stack([(x**(N-i-1)) for i in range(N)])
data1

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [15]:
x = np.array([1,2,3,4,5])
N = 5
data2 = np.vander(x,N,increasing=False)
data2

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [16]:
np.linalg.det(data1)

287.99999999999517

In [17]:
np.linalg.det(data2)

287.99999999999517

# Moving Average

In [18]:
def moving_average(N,k):
    ma_list = []
    in_array = np.array(N)
    for i in range(0,(len(N)-k+1)):
        ma_list.append(in_array[i:i+4].sum()/k)
    ma_array = np.array(ma_list)  
    return ma_array

In [19]:
moving_average([10,20,30,40,50,60,70,80,90,100],4)

array([25., 35., 45., 55., 65., 75., 85.])

In [20]:
moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

array([  5.66666667,   7.33333333,   9.        ,  10.33333333,
        31.33333333,  52.66666667,  76.33333333, 105.66666667,
       117.33333333, 143.33333333, 116.33333333])